import { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./home.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "DBU: The Homebrew Galaxy",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <header className="">
                    <nav className="flex">
                        <a className="flex-1 w-40"><h1>DBU North Galaxy</h1></a>
                        <div className="transformation-dropdown">
                            <p className="navOption">Transformations</p>
                            <div className="transformation-dropdown-content">
                                <a className="navOption" href="">Manifested Powers</a>
                                <a className="navOption" href="">Enhancement Forms</a>
                                <a className="navOption" href="">Alternate Forms</a>
                                <a className="navOption" href="">Legendary Forms</a>
                            </div>
                        </div>
                        <a className="navOption">Races</a>
                        <a className="navOption">Sign Up</a>
                        <a className="navOption">Log In</a>
                    </nav>
                </header>
                {children}
            </body>
        </html>
    );
}
