import { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "DBU: The Homebrew Galaxy",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <header className="">
                    <nav className="flex">
                        <h1 className="">DBU Galaxy</h1>
                        <a className="navOption" href="/">
                            Home
                        </a>
                        <div className="transformation-dropdown">
                            <p>Transformations</p>
                            <div className="transformation-dropdown-content">
                                <ul>
                                    <li className="navOption">
                                        <a href="">Manifested Powers</a>
                                    </li>
                                    <li className="navOption">
                                        <a href="">Enhancement Forms</a>
                                    </li>
                                    <li className="navOption">
                                        <a href="">Alternate Forms</a>
                                    </li>
                                    <li className="navOption">
                                        <a href="">Legendary Forms</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <a>Races</a>
                        <a>Sign Up</a>
                        <a>Log In</a>
                    </nav>
                </header>
                {children}
            </body>
        </html>
    );
}
